DROP TABLE PERSON;

CREATE TABLE PERSON(
ID  INTEGER PRIMARY KEY NOT NULL ,
USERNAME VARCHAR (255) NOT NULL ,
FIRSTNAME VARCHAR (255) NOT NULL ,
LASTNAME VARCHAR (255) NOT NULL ,
BIRTHDATE DATE  NOT NULL
);

--DROP SEQUENCE SEQ_PERSON;

CREATE SEQUENCE SEQ_PERSON
MINVALUE 1
MAXVALUE 9999999999
START WITH 1
INCREMENT BY 1
NOCACHE
ORDER;

--DROP TABLE ACT_PROCESS_PERSON;

CREATE TABLE ACT_PROCESS_PERSON(
ID  INTEGER PRIMARY KEY NOT NULL ,
USER_ID INTEGER NOT NULL ,
INS_PROCESS_ID VARCHAR (255) NOT NULL ,
PROCESS_STATUS CHAR (1) NOT NULL
);


--DROP SEQUENCE SEQ_ACT_PROCESS_PERSON;

CREATE SEQUENCE SEQ_ACT_PROCESS_PERSON
MINVALUE 1
MAXVALUE 9999999999
START WITH 1
INCREMENT BY 1
NOCACHE
ORDER;