DROP TABLE if EXISTS PERSON;

CREATE TABLE PERSON(
ID  BIGINT SERIAL NOT NULL ,
USERNAME VARCHAR (255) not NULL ,
FIRSTNAME VARCHAR (255) not NULL ,
LASTNAME VARCHAR (255) not NULL ,
BIRTHDATE DATE  not NULL
);
